//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PcmsTask
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ODSMEntities : DbContext
    {
        public ODSMEntities()
            : base("name=ODSMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<VW_CONSENT> VW_CONSENT { get; set; }
        public virtual DbSet<VW_CONSENT_ALIGNMENT> VW_CONSENT_ALIGNMENT { get; set; }
    }
}
