//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PcmsTask
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_CONSENT
    {
        public string PCMS_ID { get; set; }
        public string NUC_ID { get; set; }
        public string ONEKEY { get; set; }
        public System.DateTime ODSK_MODIFY_DATE { get; set; }
    }
}
