//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PcmsTask
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_CONSENT_ALIGNMENT
    {
        public string D_NUC_ID { get; set; }
        public string D_ONEKEY_ID { get; set; }
        public string H_NAME { get; set; }
        public string H_PHONE { get; set; }
        public string H_POSTCODE { get; set; }
        public string H_REGION { get; set; }
        public string H_CITY { get; set; }
        public string H_ADDR { get; set; }
        public string D_SPEC { get; set; }
        public string D_NAME { get; set; }
        public string D_EMAIL { get; set; }
        public string D_MOBILE_PHONE { get; set; }
    }
}
